//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManage.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.UserRoleMapping = new HashSet<UserRoleMapping>();
        }
    
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string UserPWD { get; set; }
        public string Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual ICollection<UserRoleMapping> UserRoleMapping { get; set; }
    }
}
