//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManage.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMapping
    {
        public int UserRoleMappingID { get; set; }
        public int UserAccountID { get; set; }
        public int UserRoleID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
